services:
  db:
    restart: always
    image: mariadb:10.11
    container_name: seafile-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWD} # Requested, set the root's password of MySQL service.
      - MYSQL_LOG_CONSOLE=true
      - MARIADB_AUTO_UPGRADE=1
    volumes:
      - seafile_sql_data:/var/lib/mysql  # Requested, specifies the path to MySQL data persistent store.
    depends_on:
      - ts-seafile
    network_mode: service:ts-seafile

  memcached:
    restart: always
    image: memcached:1.6.18
    container_name: seafile-memcached
    entrypoint: memcached -m 256
    depends_on:
      - ts-seafile
    network_mode: service:ts-seafile
          
  seafile:
    restart: always
    image: seafileltd/seafile-mc:11.0-latest
    container_name: seafile
    volumes:
      - seafile:/shared   # Requested, specifies the path to Seafile data persistent store.
    environment:
      - DB_HOST=${DB_HOST}
      - DB_ROOT_PASSWD=${DB_ROOT_PASSWD}  # Requested, the value should be root's password of MySQL service.
      - TIME_ZONE=Europe/Vienna # Optional, default is UTC. Should be uncomment and set to your local time zone.
      - SEAFILE_ADMIN_EMAIL=${SEAFILE_ADMIN_EMAIL} # Specifies Seafile admin user, default is 'me@example.com'.
      - SEAFILE_ADMIN_PASSWORD=${SEAFILE_ADMIN_PASSWORD}     # Specifies Seafile admin password, default is 'asecret'.
      - SEAFILE_SERVER_LETSENCRYPT=false   # Whether to use https or not.
      - SEAFILE_SERVER_HOSTNAME=${SEAFILE_SERVER_HOSTNAME} # Specifies your host name if https is enabled.
    depends_on:
      - db
      - memcached
      - ts-seafile
    network_mode: service:ts-seafile

  ts-seafile:
    image: tailscale/tailscale:latest
    container_name: ts-seafile
    hostname: seafile
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}
      - TS_EXTRA_ARGS=--advertise-tags=tag:container
      - TS_SERVE_CONFIG=/config/seafile.json
      - TS_STATE_DIR=/var/lib/tailscale
    volumes:
      - ${PWD}/ts-seafile/state:/var/lib/tailscale
      - ${PWD}/ts-seafile/config:/config
    restart: always
    networks:
      - seafile-net

networks:
  seafile-net:

volumes:
  seafile:
    external: true
  seafile_sql_data:
    name: seafile_sql_data
    external: false
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./seafile-mysql