services:
  duplicati:
    image: lscr.io/linuxserver/duplicati:latest
    container_name: duplicati
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Vienna
      - CLI_ARGS= #optional
    volumes:
      - duplicati_data:/config
      - backup_target:/backups
      - backup_source:/source
    ports:
      - 8200:8200
    restart: always
volumes:
  duplicati_data:
    name: duplicati_data
    external: false
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./config
  backup_target:
    name: backup_target
    external: false
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /Volumes/Backups/duplicati
  backup_source:
    name: backup_source
    external: false
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /Users/media/Projects